apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-mnist
  labels:
    app: deployment-mnist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-mnist
  template:
    metadata:
      labels:
        app: deployment-mnist
    spec:
      containers:
        - name: ml-worker
          image: filippogiorgi4/mnist:1.0
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/data/
              name: data-volume
          env:
            - name: FOLDER_PATH
              value: /var/data/
            - name: OUTPUT_PATH
              value: ml_model_prova
            - name: DATA_PATH
              value: data.csv
            - name: LOGGING_LEVEL
              value: INFO
      restartPolicy: Always
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: deployment-mnist-service
spec:
  selector:
    app: deployment-mnist
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP