apiVersion: v1
kind: Service
metadata:
  name: deployment-mnist-service
  namespace: crossplane-system
spec:
  selector:
    app: deployment-mnist
  ports:
    - protocol: TCP
      port: 30080
      targetPort: 30080
      nodePort: 30080
  type: LoadBalancer
